### ISSUE TITLE
Selecting options in Edit and View menus causes segfault

### ISSUE THREAD

**Issue by syrobee** [timw4mail/Tyro#1]
Things like Cut, Paste, Wrap Lines cause a segfault when no document is open.

**Comment by timw4mail** [comment]
Those menu items should be disabled if no file is open. Have you found a case where these menu items are not enabled?

**Comment by syrobee** [comment]
Yeah they're enabled by default for me. As soon as I build Tyro.
For context I'm on Ubuntu.

**Comment by timw4mail** [comment]
Latest commit? f4f47b081a3cbbc87966a83c283dff1319a75451

Are there disabled menu items in the file menu? I could update the menu toggling code to disable the individual menu items if that is the case.

**Comment by syrobee** [comment]
Yep, that commit.
Save, Save As, Close, Close All are disabled in the File menu.

**Comment by timw4mail** [comment]
Cool. I'll post a fix.

**Comment by syrobee** [comment]
Nice editor by the way. :)

**Comment by timw4mail** [comment]
Thanks. It was one of those projects on the backlog too long :)
